version: '3'
services:
  nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./logs/:/var/log/nginx/

  primtail:
    image: grafana/promtail:2.3.0
    command: -config.file=/mnt/config/promtail-config.yaml
    volumes:
      - ./promtail-config.yaml:/mnt/config/promtail-config.yaml
      - ./logs/access.log:/var/log/nginx/access.log
  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    command: -config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
